version: 0.2

env:
  variables:
    DBT_PROJECT_NAME: "bikestores"
    DBT_MODEL: "curated_db"
    SNOWFLAKE_ACCOUNT: "km45877.ap-southeast-2"
    SNOWFLAKE_USER: "PAUL999"
    SNOWFLAKE_ROLE: "BIKESTORES_DBT_SVC"
    SNOWFLAKE_DB: "BIKESTORES_RAW_DB"
    SNOWFLAKE_WH: "BIKESTORES_DEVELOPER_WH"
    SNOWFLAKE_SCHEMA: "PRODUCTION"
  parameter-store:
    SNOWFLAKE_PASS: /snowflake/bikestores
    SNOWFLAKE_ACCOUNT: /snowflake/bikestores
phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install --upgrade dbt
      - pip install envsubst
  pre_build:
    commands:
      - envsubst < bin/profiles/profiles.yml > bin/${DBT_PROJECT_NAME}/profiles/profiles.yml
      - cat bin/${DBT_PROJECT_NAME}/profiles/profiles.yml
  build:
    commands:
     - cd bin/${DBT_PROJECT_NAME} && dbt debug --profiles-dir profiles
     - cd bin/${DBT_PROJECT_NAME} && dbt test --data --profiles-dir profiles --models ${DBT_PROJECT_NAME}.${DBT_MODEL}
