version: 0.2

env:
  variables:
    DBT_PROJECT_NAME: "bikestores"
    SNOWFLAKE_ACCOUNT: "km45877.ap-southeast-2"
    SNOWFLAKE_USER: "PAUL999"
    SNOWFLAKE_ROLE: "BIKESTORES_DBT_SVC"
    SNOWFLAKE_DB: "BIKESTORES_RAW_DB"
    SNOWFLAKE_WH: "BIKESTORES_DEVELOPER_WH"
    SNOWFLAKE_SCHEMA: "PRODUCTION"
  parameter-store:
    SNOWFLAKE_PASS: /snowflake/bikestores
phases:
  build:
    commands:
     - pip install envsubst
     - echo $SNOWFLAKE_ACCOUNT
     - envsubst < bin/profiles/profiles.yml > bin/bikestores/profiles/profiles.yml
     - cat bin/bikestores/profiles/profiles.yml
