version: 0.2

env:
  variables:
    DBT_PROJECT_NAME: "bikestores"
    SNOWFLAKE_ACCOUNT: "km45877.ap-southeast-2"
    SNOWFLAKE_USER: "Paul999"
    SNOWFLAKE_ROLE: "BIKESTORES_DBT_SVC"
    SNOWFLAKE_DB: "BIKESTORES_RAW_DB"
    WAREHOUSE: "BIKESTORES_DEVELOPER_WH"
    SNOWFLAKE_SCHEMA: "bike_production"
  parameter-store:
    SNOWFLAKE_PASS: /snowflake/bikestores
phases:
  build:
    commands:
     - pip install --upgrade dbt
     - cd bin/${DBT_PROJECT_NAME} && dbt debug --profiles-dir=profiles
